/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/LRFF.glb 
*/

import { useGLTF } from "@react-three/drei";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function LivingRoom(props: any) {
  const { nodes, materials } = useGLTF("models/LRFF.glb");
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  );
}

useGLTF.preload("models/LRFF.glb");
